---
# This playbook installs software and creates symlinks to dotfiles

- hosts: localhost
  tasks:
    - name: Install emacs
      become: yes
      package:
        name=emacs state=latest

    - name: Install tmux
      become: yes
      package:
        name=tmux state=latest

    - name: Remove old bashrc
      file:
	path: "~/.bashrc"
        state: absent
	
    - name: Create bashrc symlink
      file:
        src: "{{playbook_dir}}/.bashrc"
        dest: "~/.bashrc"
        state: link

    - name: Remove old emacs config
      file:
	path: "~/.emacs.d/init.el"
        state: absent
	
    - name: Create emacs config symlink
      file:
        src: "{{playbook_dir}}/init.el"
        dest: "~/.emacs.d/init.el"
        state: link

    - name: Remove old tmux.conf
      file:
        state: absent
	path: "~/.tmux.conf"
	
    - name: Create tmux.conf symlink
      file:
        src: "{{playbook_dir}}/.tmux.conf"
        dest: "~/.tmux.conf"
        state: link
